version: '3.9'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5000:5432
    loan_management:
        build: .
        container_name: loan_management_backend
        environment:
            - DJANGO_SETTINGS_MODULE=loanManagement.settings
            - PYTHONPATH=/var/www
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - postgres